- name: Install python-psycopg2
  sudo: yes
  yum: pkg=python27-psycopg2 state=present

- name: Check DatabaseCluster
  sudo: yes
  stat: path=/var/lib/pgsql95/data/PG_VERSION
  register: database

- name: Create DatabaseCluster
  sudo: yes
  command: service postgresql95 initdb
  when: not database.stat.exists

- name: Start PostgreSQL service and be sure PostgreSQL is enabled
  sudo: yes
  service: name=postgresql95 state=started enabled=yes

- name: Create user for Redmine
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    name: "{{ redmine_db_user }}"
    password: "{{redmine_db_pass }}"

- name: Create database for Redmine
  sudo: yes
  sudo_user: postgres
  postgresql_db:
    name: "db_redmine"
    owner: "{{ redmine_db_user }}"
    encoding: "UTF-8"
    lc_collate: "ja_JP.UTF-8"
    lc_ctype: "ja_JP.UTF-8"
    template: "template0"

- name: Change pg_hba.conf
  sudo: yes
  template:
    src: pg_hba.conf
    dest: /var/lib/pgsql95/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0600'
  register: modify_pg_hba

- name: Restart PostgresSQL
  sudo: yes
  service: name=postgresql95 state=restarted
  when: modify_pg_hba| changed
