- name: Change default characterset
  sudo: yes
  template: src=my.cnf dest=/etc/my.cnf

- name: Start MySQL service and be sure mysqld is enabled
  sudo: yes
  service: name=mysqld state=started enabled=yes

- name: Update mysql root password for all root accounts
  sudo: yes
  mysql_user: login_user="root" login_password="" name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Delete anonymous MySQL server root user for {{ ansible_fqdn }}
  sudo: yes
  mysql_user: login_user="root" login_password={{ mysql_root_password }} user="root" host={{ ansible_fqdn }} state="absent"

- name: Delete anonymous MySQL server user for {{ ansible_fqdn }}
  sudo: yes
  mysql_user: login_user="root" login_password={{ mysql_root_password }} user="" host={{ ansible_fqdn }} state="absent"

- name: Delete anonymous MySQL server user for localhost
  sudo: yes
  mysql_user: login_user="root" login_password={{ mysql_root_password }} user="" state="absent"

- name: Remove the MySQL test database
  sudo: yes
  mysql_db: login_user="root" login_password={{ mysql_root_password }} db=test state=absent

- name: Create database for Redmine 
  mysql_db: name=db_redmine login_user="root" login_password={{ mysql_root_password }} state=present

- name: Create use for Redmine
  mysql_user: name={{ redmine_db_user }} password={{ redmine_db_pass }} login_user="root" login_password={{ mysql_root_password }} priv=db_redmine.*:ALL state=present

- name: Create database infomation file
  sudo: yes
  template: src=mysqld_root_pass.txt dest=/root/mysqld_root_pass.txt
